package theme

type ComponentType int

const (
	STATIC_TEXT ComponentType = iota
	// CPU
	CPU_PERCENTAGE_GRAPH
	CPU_PERCENTAGE_TEXT
	CPU_TEMPERATURE_TEXT
	CPU_FREQUENCY_TEXT
	CPU_LOAD_ONE_TEXT
	CPU_LOAD_FIVE_TEXT
	CPU_LOAD_FIFTEEN_TEXT
	CPU_PERCENTAGE_RADIAL
	CPU_PERCENTAGE_CHART
	CPU_FAN_TEXT
	CPU_POWER_TEXT
	CPU_VOLTAGE_TEXT
	// GPU
	GPU_PERCENTAGE_GRAPH
	GPU_TEMPERATURE_TEXT
	GPU_MEMORY_TEXT
	GPU_POWER_TEXT
	GPU_FREQUENCY_TEXT
	GPU_VOLTAGE_TEXT
	GPU_FAN_TEXT
	// Memory Virtual
	MEMORY_VIRTUAL_PERCENT_TEXT
	MEMORY_VIRTUAL_GRAPH
	MEMORY_VIRTUAL_RADIAL
	MEMORY_VIRTUAL_CHART
	MEMORY_VIRTUAL_USED_TEXT
	MEMORY_VIRTUAL_FREE_TEXT
	// Memory Swap
	MEMORY_SWAP_PERCENT_TEXT
	MEMORY_SWAP_GRAPH
	MEMORY_SWAP_RADIAL
	MEMORY_SWAP_CHART
	// Disk
	DISK_USED_PERCENT_TEXT
	DISK_FREE_TEXT
	DISK_TOTAL_TEXT
	DISK_TEMPERATURE_TEXT
	// Network Ethernet
	NET_ETH_UPLOAD_TEXT
	NET_ETH_DOWNLOAD_TEXT
	NET_ETH_UPLOADED_TEXT
	NET_ETH_DOWNLOADED_TEXT
	// Network WiFi
	NET_WLAN_UPLOAD_TEXT
	NET_WLAN_DOWNLOAD_TEXT
	NET_WLAN_UPLOADED_TEXT
	NET_WLAN_DOWNLOADED_TEXT
	// Date/Time
	TIME_HOUR_TEXT
	TIME_DAY_TEXT
	// Weather
	WEATHER_TEMPERATURE_TEXT
	WEATHER_CONDITION_TEXT
	// Volume
	VOLUME_TEXT
)
