device:
  port: AUTO
  theme: Technology_theme
  log: debug
  turn_off_on_exit: false
  sensors:
    network:
      eth: "enp3s0"
      wlo: "wlp4s0"
    cpu:
      temperature_sensor: "auto"  # e.g. "zenpower_tdie", "auto" for auto-detection
    disk:
      temperature_sensor: "auto"  # e.g. "nvme_composite", "auto" for auto-detection
    gpu:
      provider: "auto"  # auto | amd | nvidia | none
    weather:
      enabled: true
      city: "Sao Paulo,BR"
      interval: 30m
  display:
    width: 800
    height: 480
    reverse: false
    brightness: 20

#Arknights
#Blue
#Blue_vertical
#Colorful_UI_theme
#Cyan_Theme
#Cyberpunk_2077
#Dataization
#Dragon_Ball
#Dragon_Ball_vertical
#EVANGELION-01
#GIGABYTE
#Genshin
#Gundam
#Horizontal_screen_6_grid
#MIKU
#MIKU_Color_change
#Marvels_Spider-man
#NZXT_B
#NZXT_C
#NZXT_color
#NZXT_dynamic
#Pikachu_theme
#RAZER
#ROG
#ROG2
#ROG_starry_sky
#Red_Dead_Redemption_2
#Simple_future_purple_horizontal
#Simple_futuristic_purple
#Simplicity
#TaskManager
#Technology_horizontal_screen
#Technology_theme
#Techwaer
#VIPER
#White_UI_Theme
#bilibili_2233
#kiana
#purple_theme
#race_car
#sci-fi_deep_space
#starry_sky
#tide