device:
  port: AUTO
  theme: Landscape15Grid
  log: debug
  sensors:
    network:
      eth: "enp4s0"
      wlo: "wlp3s0"
  display:
    width: 800
    height: 480
    reverse: false
    brightness: 20
