device:
    api_port: 9120
    debug:
        profiling:
            enabled: false
            pprof_addr: "localhost:6060"
            pyroscope_addr: ""
    display:
        brightness: 25
        height: 720
        reverse: false
        width: 1280
    log: info
    port: AUTO
    sensors:
        cpu:
            interval: 1s
            temperature_sensor: auto
        disk:
            interval: 10s
            temperature_sensor: auto
        gpu:
            interval: 1s
            provider: auto
        memory:
            interval: 5s
        network:
            eth: enp3s0
            interval: 1s
            wlo: wlp4s0
        weather:
            city: Sao Paulo,BR
            enabled: true
            interval: 30m
    theme: GIGABYTE
    turn_off_on_exit: false
