device:
    api_port: 9120
    display:
        brightness: 20
        height: 480
        reverse: false
        width: 800
    log: debug
    port: AUTO
    sensors:
        cpu:
            interval: 1s
            temperature_sensor: auto
        disk:
            interval: 10s
            temperature_sensor: auto
        gpu:
            interval: 1s
            provider: auto
        memory:
            interval: 5s
        network:
            eth: enp3s0
            interval: 1s
            wlo: wlp4s0
        weather:
            city: Sao Paulo,BR
            enabled: true
            interval: 30m
    theme: Simple_future_purple_horizontal
    turn_off_on_exit: false
