device:
  port: AUTO
  theme: PurpleTheme
  log: debug
  sensors:
    network:
      eth: "enp4s0"
      wlo: "wlp3s0"
  display:
    width: 800
    height: 480
    reverse: false
    brightness: 20

#3.5inchTheme2
#5inchTheme2
#5inchTheme2Radial
#bash-dark-green
#bash-dark-green-gpu
#BigClock
#CyanTheme
#Cyberpunk
#Cyberpunk-net
#DragonBall5inch
#Landscape15Grid
#Landscape6Grid
#LandscapeEarth
#LandscapeMagicBlue
#NZXT_B
#NZXT_BLUR
#NZXT_C
#NZXT_color
#NZXT_dynamic
#PurpleTheme
#Terminal
